//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public TblProduct()
        {
            this.TblTransItem = new HashSet<TblTransItem>();
        }
    
        public int ProductID { get; set; }
        public int ProductType { get; set; }
        public string ProName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
    
        public virtual TblProType TblProType { get; set; }
        public virtual ICollection<TblTransItem> TblTransItem { get; set; }
    }
}
