//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransItem
    {
        public int TransItemID { get; set; }
        public string TransID { get; set; }
        public int ProductID { get; set; }
        public short ProductCount { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblTransaction TblTransaction { get; set; }
    }
}
